except NameError as e:
print('there was an error with the code')
print('you keyed in a test value'\'where a number was expected')
else:
print('solving(x/2)/(x-y) for value x='\,x,'and y',y,'we get the result',z)
finally:
print('clean up code goes here')